-- =============================================================================
-- BitGo Shielded Vault Integration
-- Add BitGo balances and fresh address tracking
-- =============================================================================

-- 1. Update balances table to include BitGo specific tokens (e.g., tETH on BitGo Testnet)
ALTER TABLE balances 
ADD COLUMN IF NOT EXISTS bitgo_teth_balance NUMERIC DEFAULT 0;

-- 2. Create a table for Fresh Addresses (Stealth Addresses Simulation)
-- This table maps a user's wallet/account to multiple unique BitGo addresses
CREATE TABLE IF NOT EXISTS bitgo_addresses (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  username TEXT NOT NULL,
  wallet_address TEXT NOT NULL, -- Owner's primary wallet
  bitgo_address TEXT NOT NULL UNIQUE, -- The fresh address generated by BitGo
  label TEXT, -- Optional label for the address (e.g., "Payment for Invoice #123")
  is_used BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_bitgo_addresses_username ON bitgo_addresses(username);
CREATE INDEX IF NOT EXISTS idx_bitgo_addresses_bitgo ON bitgo_addresses(bitgo_address);

-- 3. Update payments table to include currency and source info if not already there
ALTER TABLE payments 
ADD COLUMN IF NOT EXISTS currency TEXT DEFAULT 'ETH';

-- 4. Enable RLS for the new table
ALTER TABLE bitgo_addresses ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow all for bitgo_addresses (anon)"
  ON bitgo_addresses FOR ALL
  USING (true)
  WITH CHECK (true);
